### ISSUE TITLE
중복 함수 호출 문제

### ISSUE THREAD

**Issue by jkorea2** [parkkihyeon/17Capstone_project#15]
if, else if, else 로 라인이 내려가며 다른 기능을 하는 것이 아니라 결국 공통된 기능을 하고 있으므로 조건에 해당하는 부분을 parameter로 보내 처리하는 등의 다른 방식을 활용하여 코드 자체의 중복된 호출 줄이기

**Comment by kmu-yoonsh** [comment]
중복 함수 호출이 아니라 중복 코드의 문제
