### ISSUE TITLE
소스코드 주석

### ISSUE THREAD

**Issue by jkorea2** [parkkihyeon/17Capstone_project#8]
전체 코드에 대해 자세한 주석 달기

**Comment by kmu-yoonsh** [comment]
주석을 달기전에 변수나 함수명을 수정해서 readable  하다면 주석은 필요없습니다.

**Comment by kmu-yoonsh** [comment]
모든 이슈들에 label, milestone 설정이 되어 있지 않습니다. 
수업에서 지켜야 하는 github 가이드라인을 지켜주세요.
